[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/admin/.cache/noctalia/placeholder.json"

[templates.starship_palette_apply]
input_path = "~/.config/noctalia/templates/starship-apply-trigger.txt"
output_path = "~/.cache/noctalia/starship-apply-trigger"
post_hook = "PALETTE_FILE=\"$HOME/.cache/noctalia/starship-palette.toml\" /etc/xdg/quickshell/noctalia-shell/Scripts/bash/template-apply.sh starship"
